// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByU7cKIqUzBoFoKGOUoAebZyE2ELDk8Y0',
    appId: '1:174855525825:web:bed0901518224161210b40',
    messagingSenderId: '174855525825',
    projectId: 'final-year-project-85f40',
    authDomain: 'final-year-project-85f40.firebaseapp.com',
    storageBucket: 'final-year-project-85f40.firebasestorage.app',
    measurementId: 'G-9FR2WYH2D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZ_Aj9ZPmmVQ5MXOY1taVS_F6DMxX990',
    appId: '1:870455473139:android:48bd3fa583187596b71886',
    messagingSenderId: '870455473139',
    projectId: 'final-year-project-e7cc7',
    storageBucket: 'final-year-project-e7cc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbGeVBxSZWDXG_3SmoVgX_45vgXU72JJU',
    appId: '1:870455473139:ios:9eca9b7872d113b2b71886',
    messagingSenderId: '870455473139',
    projectId: 'final-year-project-e7cc7',
    storageBucket: 'final-year-project-e7cc7.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCktNCQa8QRtaVyEv3OnCqkpvwZURHZQ-s',
    appId: '1:174855525825:ios:7e5e94f671327027210b40',
    messagingSenderId: '174855525825',
    projectId: 'final-year-project-85f40',
    storageBucket: 'final-year-project-85f40.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByU7cKIqUzBoFoKGOUoAebZyE2ELDk8Y0',
    appId: '1:174855525825:web:c9cca3f4f9ed4e41210b40',
    messagingSenderId: '174855525825',
    projectId: 'final-year-project-85f40',
    authDomain: 'final-year-project-85f40.firebaseapp.com',
    storageBucket: 'final-year-project-85f40.firebasestorage.app',
    measurementId: 'G-JFE25XW9X3',
  );
}